[tool.poetry]
name = "iplist checker"
version = "0.1.0"
description = ""
authors = ["TFSID"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
selenium = "^4.22.0"
icecream = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
